### PR TITLE
Adds in Google Analytics tracking

### PR DESCRIPTION
**Pull request by TessMyers**

### CODE REVIEW

**Comment by TessMyers** [comment]
I just noticed that the deployed app has a much better favicon...  where is that actually coming from?

**Comment by TessMyers** [comment]
The only important fix here is that the 'fork me' banner link is now accurate. Go click the banner on the currently deployed app for a laugh.

**Comment by tgrrtt** [comment]
@TessMyers not sure, when I go there a favicon doesnt show up. what are you seeing?

**Comment by TessMyers** [comment]
Ahh, I should have taken a screenshot. It was only on regexpress.io and looked kind of like an OM symbol or something. I have no idea where it could have come from.

**Comment by tgrrtt** [comment]
http://www.gandi.net/Did it look like the symbol on that website? They're our registrar.

**Pull request merged**
